name: Build win_ui_auto
on:
  push:
    branches:
      - main
    # 只有指定文件变化才运行
    paths:
      - win_ui_auto/main.py
      - win_ui_auto/pyproject.toml
      - .github/workflows/build_win_ui_auto.yml
  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install Dependencies
        run: |
          cd win_ui_auto
          uv sync

      - name: Build
        run: |
          uv run build.py
        env:
          PYTHONUTF8: 1

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: win_ui_auto_${{ runner.os }}
          path: |
            win_ui_auto/build/**
          include-hidden-files: true
