name: Build EXE with uv (on win_ui_auto changes)

on:
  push:
    branches:
      - main
    paths:
      - 'win_ui_auto/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5 # 版本从 v4 更新到 v5

      - name: Install uv
        run: pip install uv

      - name: Install dependencies with uv
        working-directory: ./win_ui_auto
        run: |
          uv venv
          uv pip install -r requirements.txt
          uv pip install pyinstaller

      - name: Run build.py
        working-directory: ./win_ui_auto
        run: uv run python build.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v5 # 版本从 v4 更新到 v5
        with:
          name: win_ui_auto_exe
          path: ./win_ui_auto/dist/
